version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: eventra-postgres-db
    environment:
      POSTGRES_DB: eventra_db
      POSTGRES_USER: eventra_user
      POSTGRES_PASSWORD: eventra_password
    ports:
      - "55432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: unless-stopped
