version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: eventra-postgres-db
    environment:
      POSTGRES_DB: eventra_db
      POSTGRES_USER: eventra_user
      POSTGRES_PASSWORD: eventra_password
    ports:
      - "45432:5432"
    volumes:
      # Persistent data
      - ./volumes/postgres:/var/lib/postgresql/data
      # Initialization script
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # Твоя Кафка и остальное (оставляем как было)